### ISSUE TITLE
キャッシュ 暗号化

### ISSUE THREAD

**Issue by kazuya-sakamoto** [team-up-develop/teamup-develop-front#138]
## 概要
Vuexにて使用しているLocalStorageにて
セキュリティの観点から、格納する値を暗号化して保持する。

### 現状のLocalStorage
<img width="772" alt="スクリーンショット 2021-01-08 23 03 30" src="https://user-images.githubusercontent.com/56709557/104024046-deba5680-5205-11eb-8614-3f76dfe96a80.png">

## やることリスト
- [ ] ローカルストレージのValue を暗号化し、解読ができないようにする。
- [ ] 暗号化しても現状と同じような挙動ができるようにする（暗号化したものを取得した時、正常な値に戻す）

**Comment by Kazuya-Sakamoto** [comment]
jwt(JSON Web Token) を使用するため、ローカルストレージの値が変わってもログイン周りには支障がないため、一旦優先順位下げます。
